### ISSUE TITLE
Command not found

### ISSUE THREAD

**Issue by omarsafwany** [psliwa/image-optimizer#16]
I ran the following command on the server:
`sudo apt-get install optipng pngquant pngcrush gifsicle jpegoptim`
I ran the example as stated with the `ignore_errors` flag set to `false` but I keep getting command not found.

**Comment by mashuble** [comment]
Same problem

**Comment by markdieselcore** [comment]
Same. Any solutions?

**Comment by markdieselcore** [comment]
I ended up fixing this by having to manually specify the binary paths like so:

    $factory = new OptimizerFactory([
        'ignore_errors' => true,
        'pngquant_bin'  => '/usr/bin/pngquant',
        'pngcrush_bin'  => '/usr/bin/pngcrush',
        'pngout_bin'    => '/usr/bin/pngout',
        'optipng_bin'   => '/usr/bin/optipng',
        'advpng_bin'    => '/usr/bin/advpng',
        'jpegtran_bin'  => '/usr/bin/jpegtran',
        'jpegoptim_bin' => '/usr/bin/jpegoptim',
        'gifsicle_bin'  => '/usr/bin/gifsicle',
    ]);

Installs on the aforementioned binaries were pretty easy with the exception of pngout. I couldn't apt-get that binary package, so I ended up finding a tutorial online that guides you through the process of wget and moving it to the appropriate directory.

To find where your binaries are installed on your server, SSH into your server and run ``whereis jpegtran`` or whatever binary you're looking for. If it is installed it will return the binary path.

**Comment by thomaswelton** [comment]
For me on a mac installing with homebrew `brew install pngquant optipng pngcrush advancecomp`

**Comment by psliwa** [comment]
This library tries to guess where binaries are. In most cases it should work, but it depens what system do you use, how it is configured etc. It uses `ExecutableFinder` from `Process` component of symfony. There is a way to configure binaries explicitly so I don't see here an issue.
