### ISSUE TITLE
Generated command is wrong?

### ISSUE THREAD

**Issue by koichirose** [psliwa/image-optimizer#17]
I'm having the following issue on ubuntu (using version 1.0.6):
```
Fatal error: Uncaught exception 'ImageOptimizer\Exception\Exception' with message
'Command failed, return code: 1, command: /usr/bin/jpegtran '-optimize' '-progressive' '-outfile' '/home/koichirose/public_html/dev/system/../assets/images/news/test_image.jpg' '/home/koichirose/public_html/dev/system/../assets/images/news/test_image.jpg' 1> /dev/null 2> /dev/null'
in /home/koichirose/public_html/dev/vendor/ps/image-optimizer/src/ImageOptimizer/Command.php:46 

Stack trace: #0 /home/koichirose/public_html/dev/vendor/ps/image-optimizer/src/ImageOptimizer/CommandOptimizer.php(29): ImageOptimizer\Command->execute(Array)
# 1 /home/koichirose/public_html/dev/vendor/ps/image-optimizer/src/ImageOptimizer/ChainOptimizer.php(24): ImageOptimizer\CommandOptimizer->optimize('/home/koichirose/pub...')
# 2 /home/koichirose/public_html/dev/vendor/ps/image-optimizer/src/ImageOptimizer/SmartOptimizer.php(32): I in /home/koichirose/public_html/dev/vendor/ps/image-optimizer/src/ImageOptimizer/Command.php on line 46
```

Running the exact same command without quotes from the command line works fine:
```
/usr/bin/jpegtran -optimize -progressive -outfile /home/koichirose/public_html/dev/system/../assets/images/news/test_image.jpg /home/koichirose/public_html/dev/system/../assets/images/news/test_image.jpg
```

I'm running it like this just to test:

``` php
$full_path = '/home/koichirose/public_html/dev/system/../assets/images/news/test_image.jpg';
$factory = new \ImageOptimizer\OptimizerFactory(array('ignore_errors' => false));
$optimizer = $factory->get();
$optimizer->optimize($full_path);
```

**Comment by prthorun** [comment]
Ran into the same issue. The solution to overwrite files with the optimized version is using -outfile {}.

Unfortunately this argument is hardcoded in the library, class OptimizerFactory line 105-107 as follows:

```
function ($filepath) {
    return array('-outfile', $filepath);
}
```

**Comment by approached** [comment]
Same issue on my extended package.
https://travis-ci.org/approached/laravel-image-optimizer/jobs/151516271

Can try to give more write rights, like this:
chmod 777 -R /home/koichirose/public_html/dev/system/../assets/images/news/

**Comment by approached** [comment]
Which OS you are use? I just updated the package and now it works fine. Look in my install script:
```yml
  - wget http://de.archive.ubuntu.com/ubuntu/pool/universe/p/pngquant/pngquant_2.5.0-1_amd64.deb
  - sudo dpkg -i pngquant_2.5.0-1_amd64.deb

  - wget https://launchpad.net/ubuntu/+archive/primary/+files/gifsicle_1.88-1_amd64.deb
  - sudo dpkg -i gifsicle_1.88-1_amd64.deb

  - wget https://launchpad.net/ubuntu/+archive/primary/+files/jpegoptim_1.4.3-1_amd64.deb
  - sudo dpkg -i jpegoptim_1.4.3-1_amd64.deb

#  - sudo apt-get install -y pngquant gifsicle jpegoptim (not usable OS is old in travis)
  - pngquant --version # 2.5.0 (June 2015)
  - jpegoptim --version # jpegoptim v1.4.3  x86_64-pc-linux-gnu (libjpeg version: 8d  15-Jan-2012)
  - gifsicle --version # LCDF Gifsicle 1.88
```

**Comment by koichirose** [comment]
It works for me if I select "jpegoptim" manually. using the "smart" optimizer automatically select "jpegtran" and that command fails.

**Comment by zorobabel** [comment]
I tested this issue on Windows 8.1 and CentOS and get:

```php
ImageOptimizer\Exception\Exception

Command failed, return code: 4, command: "D:\ImageOptimization\pngquant.exe" "--force" "--quality 70" "--ext=.png" "--" "D:\Development\PHP\tests\image-optimizer\a.png"
```
```bash
D:\ImageOptimization\pngquant.exe: unknown option -- quality 70
```

The generated command is wrong but this works fine (removing double quotes for `--quality 70`):

```bash
"D:\ImageOptimization\pngquant.exe" "--force" --quality 70 "--ext=.png" "--" "D:\Development\PHP\tests\image-optimizer\a.png"
```

**Comment by ChristianTheMinery** [comment]
Just encountered this issue also, running PHP from the command line of an AWS server.

**Comment by psliwa** [comment]
I am not able to help if I won't get `jpegtran` and other stuff versions. Of course the output (from both: stdout and stderr) of the command generated by the library would be essential as well. @ChristianTheMinery Can you provide such info?

**Comment by robotE13** [comment]
Hi! 
Jpegtran optimizer creates command with quoted jpegtran options. Like this "C:\Windows\jpegtran.EXE" "-optimize" "-progressive" "-copy none" "-outfile" "path-to-file" "path-to-file". 

It is not works. If i run this command from cmd then jpegtran shows help screen and do nothing. With removed quotes it work well.

**Comment by psliwa** [comment]
Since `2.0.0` version a way of generating command has changed (`symfony-process` component is used), so it should not be a problem anymore.
