### ISSUE TITLE
Use the Symfony\Component\Process for executing commands

### ISSUE THREAD

**Issue by dmnc** [psliwa/image-optimizer#21]
This seems like a no brainer given it is already a dependency. 

It would add the ability to have timeouts, analyse exit codes, etc.

If this is something you're keen on I'd be happy to have a stab at a PR.

**Comment by psliwa** [comment]
Yes, timeouts would be nice improvement, because optimizing big images may last long time. If you are still interested, PR is welcome. If not, maybe I will implement this, but it doesn't have big priority.

**Comment by psliwa** [comment]
It will be done in `2.0.0` version - not released yet. Also there will be new configuration option: `single_optimizer_timeout_in_seconds`.
