### ISSUE TITLE
Cannot find `ExecutableFinder` class

### ISSUE THREAD

**Issue by soravgarg123** [psliwa/image-optimizer#28]
Fatal error: Class 'Symfony\Component\Process\ExecutableFinder' not found in /opt/lampp/htdocs/test/image-optimizer/src/ImageOptimizer/OptimizerFactory.php on line 25

I think this class doesn`t exist or using wrong path,

also OptimizerFactory class using multiple classes inside single namespace

**Comment by psliwa** [comment]
Probably it is a problem with yours autoloader, I can see `ExecutableFinder` class is still available in `symfony/process` library so everything should be ok. If there is still a problem, can you provide more info? Try to find `ExecutableFinder.php` file in yours `vendor` dir? I believe even if you have still problems with `ExecutableFinder` this is not a problem with this library.
