### ISSUE TITLE
What am I doing wrong?

### ISSUE THREAD

**Issue by franciscoortiz16** [psliwa/image-optimizer#34]
Hi, I followed the example, and nothing is happening. Libraries are loaded OK, but images (jpg for example) are not reducing its size.
Is there a way to check if I am doing everything right?
My code is:

error_reporting(E_ALL);
ini_set('display_errors', 1);
$loader = require __DIR__.'/../vendor/autoload.php';
$loader->addPsr4('ImageOptimizer\\', __DIR__.'/ImageOptimizer');
$factory = new \ImageOptimizer\OptimizerFactory(array('ignore_errors' => false));
$optimizer = $factory->get();
$filepath = 'imagen.jpg';
$optimizer->optimize($filepath);
 //optimized file overwrites original one

Then, I get the following error: "Fatal error: Uncaught exception 'ImageOptimizer\Exception\Exception' with message 'All optimizers failed to optimize the file: imagen.jpg' "

Thanks in advance!

**Comment by franciscoortiz16** [comment]
Is there a way to check if I am doing everything right?

**Comment by Jlomaka** [comment]
I have the same question, I did everything as it is written in the example but nothing happens can the author still deign to answer this question? And then I myself spent half a day to understand what the trouble is and did not find the answer

**Comment by nlzet** [comment]
@franciscoortiz16 @Jlomaka see https://github.com/psliwa/image-optimizer/issues/30, It is possible you are experiencing the same problem. (For me it worked locally, in production nothing happened, debugging got me to this problem)

**Comment by dcdeiv** [comment]
same

**Comment by potnii** [comment]
same issue

**Comment by nlzet** [comment]
I think it is best to debug the actual command sent to execute the optimization, and try to run it manually on the server/machine. You will probably see a more verbose output to identify your problems.

**Comment by psliwa** [comment]
I added new section to the README that answers this question: https://github.com/psliwa/image-optimizer#i-got-all-optimizers-failed-to-optimize-the-file
