### ISSUE TITLE
Help with image-optimizer

### ISSUE THREAD

**Issue by steven26** [psliwa/image-optimizer#36]
Dear sir,

I installed all the needed libraries on Centos 6.
If i open the file OptimizersTest.php, i get a blank screen, no errors, but the size of images in folder Resources are not changed.

And than i am lost how to use the image-optimizer.
This will give the error:
Fatal error: Class 'ImageOptimizer\OptimizerFactory'

`<?php
namespace ImageOptimizer;

use ImageOptimizer\Exception\Exception;
error_reporting(E_ALL);
ini_set('display_errors', 1);
require_once 'PHPUnit/Autoload.php';
$factory = new \ImageOptimizer\OptimizerFactory();
$optimizer = $factory->get();
$filepath = 'Resources/sample.jpg';
$optimizer->optimize($filepath);
?>`

Help would be appreciated.

Kind regards,

Steven

**Comment by psliwa** [comment]
You need to use composer in order to install and use this library - I will add info about this to the README soon. So assuming that you know what composer is and how to use it, you need to invoke `composer require ps/image-optimizer:1.1.*`.
