### ISSUE TITLE
Suggestion: add a .gitattributes file

### ISSUE THREAD

**Issue by freekmurze** [psliwa/image-optimizer#43]
Right now, when installing the package on a production server, the tests get installed as well. This can be avoided by adding a `.gitattributes` file. In this file you can specify which files should not be used when installing the package somewhere.

Here's an example of such a file: https://github.com/spatie/laravel-backup/blob/master/.gitattributes

There are no downsides of adding such a file, so I highly recommend adding one to this package.

**Comment by psliwa** [comment]
Added.
