### ISSUE TITLE
How to specify quality of the image

### ISSUE THREAD

**Issue by janakaonline** [psliwa/image-optimizer#5]
Hi, thanks for the awesome library. I'm using jpegoptim. i want to specify the quality of the image when optimizing. Currently arguments are set to --strip-all, --all-progressive. is there a way I can specify the arguments for jpegoptim?

Thanks

**Comment by delia-curiel** [comment]
hi, I have the same question..... I don't know how to pass additional arguments (as --max=90 for example)

**Comment by psliwa** [comment]
I will review and merge it asap.
