### ISSUE TITLE
Update Symfony deps

### ISSUE THREAD

**Issue by mrTimofey** [psliwa/image-optimizer#50]
Hello!
I am trying to use this package with Laravel 5.6 and I can not install it with composer because of Symfony package version. There is a conflict between Laravel deps (which uses symfony/process 4.* for example) and image-optimizer (which can only use 3.* version).
I guess there are no any changes that can break the package so may be you can just safely add ~4.0 to your deps?

**Comment by psliwa** [comment]
Added: https://github.com/psliwa/image-optimizer/pull/54. Version `1.1.3` is compatible with symfony 4.
