### ISSUE TITLE
Uncaught ImageOptimizer\Exception\Exception All optimizers failed to optimize the file

### ISSUE THREAD

**Issue by bggcs** [psliwa/image-optimizer#55]
My code is bellow (sample.php)

```
<?php
error_reporting(E_ALL);
ini_set('display_errors', 1);

require_once 'vendor/autoload.php';

$factory = new \ImageOptimizer\OptimizerFactory(array('ignore_errors' => false));

$optimizer = $factory->get();

$filepath = __DIR__."/test.jpg";

$optimizer->optimize($filepath);
?>
```

but it appear error

Fatal error: Uncaught ImageOptimizer\Exception\Exception: All optimizers failed to optimize the file: /var/www/html/opt/test.jpg in /var/www/html/opt/vendor/ps/image-optimizer/src/ImageOptimizer/ChainOptimizer.php:40
Stack trace: #0 /var/www/html/opt/vendor/ps/image-optimizer/src/ImageOptimizer/SmartOptimizer.php(32): ImageOptimizer\ChainOptimizer->optimize('/var/www/html/o...')
#1 /var/www/html/opt/sample.php(13): ImageOptimizer\SmartOptimizer->optimize('/var/www/html/o...')
#2 {main} thrown in /var/www/html/opt/vendor/ps/image-optimizer/src/ImageOptimizer/ChainOptimizer.php on line 40

what happen??

**Comment by cusster** [comment]
@bggcs I suppose you don't any optimizers installed for JPEGs. See [Supported Optimizers](https://github.com/psliwa/image-optimizer#supported-optimizers).

**Comment by psliwa** [comment]
In order to check details, you can configure logger - logs should tell you everything, all errors are logged:

```php
<?php

namespace YourNamespace;

class StdoutLogger extends \Psr\Log\AbstractLogger {
  public function log($level, $message, array $context = array()) {
    echo $message."\n";
  }
}

$factory = new \ImageOptimizer\OptimizerFactory(array(), new StdoutLogger());

$factory->get()->optimize('yourfile.jpg');
