### ISSUE TITLE
 ErrorException in Command.php line 38: Undefined variable: outputLines

### ISSUE THREAD

**Issue by congloi** [psliwa/image-optimizer#57]
I used this package few month ago, all was going ok. but today, get error

ErrorException in Command.php line 38:
Undefined variable: outputLines

line 38 is:   exec($command, $outputLines, $result);

help me check, I don't know why, I don't edit or do anything in my server.

my version is 1.1, using pngquant to optimized

**Comment by tomopongrac** [comment]
I know that you write that you dont change anything on your server but check in your php.ini file do you have exec function disabled (exec function must be enabled).

**Comment by psliwa** [comment]
From `1.2.2` version I made clear error message when `exec` function is disabled.
