### ISSUE TITLE
composer install issu

### ISSUE THREAD

**Issue by oveysrostami** [psliwa/image-optimizer#59]
Hi
When I exec composer "composer require ps/image-optimizer" receive this message : 
`Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for ps/image-optimizer dev-master -> satisfiable by ps/image-optimizer[dev-master].
    - Can only install one of: ps/image-optimizer[1.2.0, dev-master].
    - Installation request for ps/image-optimizer ^1.2 -> satisfiable by ps/image-optimizer[1.2.0].

Installation failed, reverting ./composer.json to its original content.
`

What is The Problem ?!

**Comment by psliwa** [comment]
It should be fixed for `1.2.1` version.
