### ISSUE TITLE
Optimization doesn't work

### ISSUE THREAD

**Issue by TheSDTM** [psliwa/image-optimizer#6]
Hello, can you help me? I installed your library using composer, installed all libraries (optipng, etc.), wrote
$factory = new \ImageOptimizer\OptimizerFactory(array('ignore_errors' => false));
But file is not optimized.
I tried:
$filepath = 'Upload/'.$data['name'];
        try {
            $optimizer->optimize($filepath);
        } catch (CommandNotFound $e) {
            echo "string";
}

But 'echo "string";' doesn't appear on my screen.

**Comment by psliwa** [comment]
How do you know the file is not optimized?

**Comment by TheSDTM** [comment]
I tried to optimize with optipng using command line with, then i tried to optimize it using script. Size of the first file is less than second.

**Comment by codeliter** [comment]
Same issue here and no error is shown or returned
