### ISSUE TITLE
pngquant makes small images larger in rare cases

### ISSUE THREAD

**Issue by tominventisbe** [psliwa/image-optimizer#60]
This can also occur to `optipng`, but it is smart enough to skip the process if the output is larger than the input.

Apparently `pngquant` also has an option for this via `--skip-if-larger`, but it is not passed in the defaults in the OptimizerFactory.

Would it be possible to enable this option by default? I can enable it myself, of course, but it would be a more sane default that would improve usage for everyone :smile: .

**Comment by psliwa** [comment]
Fixed.
