### ISSUE TITLE
jpg

### ISSUE THREAD

**Issue by hooman-pro** [psliwa/image-optimizer#62]
Your library is very good and useful in png images.
but about jpg images tinypng.com make images very optimizer than this library!
is therer any way to have better optimization for jpg?? (like installing an other jpg optimzer )

**Comment by psliwa** [comment]
I think it is their propertiary solution and they don't say what algorithm / optimizer they use. I can add optimizer what uses they service as an optimizer, there is php client for their api: https://github.com/tinify/tinify-php.
