### ISSUE TITLE
Release 1.2.2 not available via composer

### ISSUE THREAD

**Issue by MacGyer** [psliwa/image-optimizer#69]
Hi there,

just tried to update the package to your last release, which is 1.2.2. But `composer update` failed with the following message:

```
  Problem 1
    - The requested package ps/image-optimizer ~1.2.2 exists as ps/image-optimizer[1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.0.6, 1.1.0, 1.1.1, 1.1.2, 1.1.3, 1.2.0, 1.2.1, dev-master] but these are rejected by your constraint.
```

I quick check at https://packagist.org/packages/ps/image-optimizer revealed, that the 1.2.2 release is missing?!

Could you please check this?

Thanks

**Comment by psliwa** [comment]
Thanks for letting know. Right now `1.2.2` version should be available.
