### ISSUE TITLE
custom_optimizers and args do not work

### ISSUE THREAD

**Issue by vitadisplays** [psliwa/image-optimizer#72]
Parenthesis in OptimizerFactory Row 129 not correctly set in version 1.2.2.

new Command($this->executable(**$options['command'], isset($options['args'])** ? $options['args'] : array())))

to 

 new Command($this->executable($options['command']), isset($options['args']) ? $options['args'] : array()))

I try webp optimizing with cwebp.

Here some some option hints:

        'custom_optimizers' => array(
            'webp' => array(
                'command' => 'cwebp',
                'args' => array(
                    '-quiet',
                    '-m',
                    6,
                    '-pass',
                    10,
                    '-mt',
                    '-o',
                    $outputfile
                ) 
            )
        )

At the moment, the output option must be defined.

It will be nice to support webp directly.

**Comment by psliwa** [comment]
Thanks for letting know. I've released `1.2.3` with the fix. The newest version (`2.0.1`) is not affected by this issue.

I will have a look later at `webp`, but if I add support for this format, it will be only in `2.0.x` branch.

**Comment by vitadisplays** [comment]
Thanks for the fast replay,
at the moment my software runs under php5.6. Only the 1.2.x brunch + custom_optimizers is possible to support webp.
