### ISSUE TITLE
image doesn't change 

### ISSUE THREAD

**Issue by nadia-am** [psliwa/image-optimizer#76]
I install this lib on local to optimize my picture, but after basic usage noting change about the photoes!
I used logger as recommended in docs,
the error message is : 
"Command failed, return code: 1, command: jpegtran -optimize -progressive -outfile "pics/t.jpg" "pics/t.jpg", stderr: 'jpegtran' is not recognized as an internal or external command,
But don't have any idea how to solve it!
![image](https://user-images.githubusercontent.com/11175468/113094525-10402e00-9207-11eb-9097-142ab4c7e9f3.png)

**Comment by psliwa** [comment]
Hi, it is not enough to install this lib but also you need to install at least one of supported optimizers: https://github.com/psliwa/image-optimizer#supported-optimizers. In your case you need to install also eg `jpegtran` (http://jpegclub.org/jpegtran/)
