### ISSUE TITLE
Exception when running optimize

### ISSUE THREAD

**Issue by SamarRizvi** [psliwa/image-optimizer#9]
Here is the exception I receive with running optimize:

ImageOptimizer\Exception\Exception: Command failed, return code: 1, command: C:^\Program Files^\pngquant^\pngquant.EXE \"--force\" \"--ext=.png\" \"--\" \"F:\laragon\www\demo\images\uploads\ec498dcfc950e8df339c81ec73ac70e2b46f87b2.png\" in F:\laragon\www\demo\vendor\ps\image-optimizer\src\ImageOptimizer\Command.php

. On the other hand, if I run  pngquant "--force" "--ext=.png" "--" "F:\laragon\www\demo\images\uploads\43d67cba7a951378485882e5b515c825943f7d0a.png"directly in shell, it works fine.

**Comment by psliwa** [comment]
The issue has been fixed by #11
